# Generated by Django 5.2.16 on 2026-08-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_customer_options_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo de movimento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Saldo após movimentação')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='accounts.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
