# Generated by Django 5.2.16 on 2026-08-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='source',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venda'), ('ADJUSTMENT', 'Ajuste'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Origem'),
        ),
    ]
