# Generated by Django 5.2.16 on 2026-08-21 04:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo inicial')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo de Fechamento')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado')], default='OPEN', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-opened_at'],
            },
        ),
    ]
