# Generated by Django 5.2.16 on 2026-08-21 04:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=10, verbose_name='Tipo de movimento')),
                ('source', models.CharField(choices=[('SALE', 'Venda'), ('PURCHASE', 'Compra'), ('ADJUSTMENT', 'Ajuste'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Origem')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.cashregister', verbose_name='Caixa')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-created_at'],
            },
        ),
    ]
