# Generated by Django 5.2.16 on 2026-08-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='accounts.product', verbose_name='Produto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='accounts.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto por Fornecedor',
                'verbose_name_plural': 'Produtos por Fornecedor',
                'constraints': [models.UniqueConstraint(fields=('product', 'supplier'), name='unique_product_supplier')],
            },
        ),
    ]
