# Generated by Django 5.2.16 on 2026-08-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_options_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
